=== OneKey-Network/addressability-framework/mvp-spec/json-schemas/delete-ids-prefs-response.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "delete-ids-prefs-response",
  "title": "DELETE /v1/ids-prefs response",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "sender": {
      "$ref": "domain.json",
      "description": "The domain name of the sender of this response (the operator domain name)"
    },
    "receiver": {
      "$ref": "domain.json",
      "description": "The domain name of the receiver of this response (the website)"
    },
    "timestamp": {
      "$ref": "timestamp.json"
    },
    "signature": {
      "$ref": "signature.json",
      "description": "Signature based on input:\n```\nsender + '\\u2063' +\nreceiver + '\\u2063' +\ntimestamp\n```"
    },
    "body": {
      "$ref": "ids-and-optional-preferences.json",
      "description": "Contains an empty list of identifiers and undefined preferences for delete-ids-prefs-response"
    }
  },
  "required": [
    "sender",
    "receiver",
    "timestamp",
    "signature"
  ],
  "description": "A success code is returned in case of successful deletion of the identifiers and preferences"
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/getIdPrefsResponse_unknown.json
{
  "body": {
    "identifiers": [
      {
        "persisted": false,
        "version": 0,
        "type": "prebid_id",
        "value": "2e71121a-4feb-4a34-b7d1-839587d36390",
        "source": {
          "domain": "operator.prebidsso.com",
          "timestamp": 1643041140000,
          "signature": "/97uDMKRyaW1v2MH4UbU6UNRft/v+1bJV0vpmArVc3l9ErOhCuM2nsewgAI5w9HjFJbzvdLlTOTlTjTlZCdw8w=="
        }
      }
    ]
  },
  "sender": "operator.prebidsso.com",
  "receiver": "advertiser.com",
  "timestamp": 1643041150000,
  "signature": "GIqz3qO/aYp/tCs1wLD/t4UQJul0RZ2HgxnWGHGMRi42Wl6FUqrrEoiIp1V5YkpVABqzwsZ0SXSRybnbAtYNUg=="
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/getIdsPrefsResponse_unknown.json
{
  "body": {
    "identifiers": [
      {
        "persisted": false,
        "version": 0,
        "type": "paf_browser_id",
        "value": "2e71121a-4feb-4a34-b7d1-839587d36390",
        "source": {
          "domain": "operator.prebidsso.com",
          "timestamp": 1643041140000,
          "signature": "PPhtH9vaPP1SXeGXOFzOcMmbOiJ/3or0+o5YUli0NQfgLQ087kuAAUvivPkcyyRza1Eorq7C1EXmmJRxEBRp8A=="
        }
      }
    ]
  },
  "sender": "operator.prebidsso.com",
  "receiver": "advertiser.com",
  "timestamp": 1643041150000,
  "signature": "yjglI9Fq8jfHTOk2PjE+coq8oLwsSbULoBh96tv8o4njN6v0bFUl0S1vD3Dq9Jz++7ibbUEzYA5ujaCR1QASfw=="
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/postIdPrefsResponse.json
{
  "body": {
    "identifiers": [
      {
        "version": 0,
        "type": "prebid_id",
        "value": "7435313e-caee-4889-8ad7-0acd0114ae3c",
        "source": {
          "domain": "operator.prebidsso.com",
          "timestamp": 1642504380000,
          "signature": "RYGHYsBUEwMgFgOJ9aUQl7ywl4xnqdmwWIgPbaIowbXbmZAFKLa7mcBJQuWh1wEskpu57SHn2mmCF6V5+cESgw=="
        }
      }
    ],
    "preferences": {
      "version": 0,
      "data": {
        "opt_in": true
      },
      "source": {
        "domain": "cmp.com",
        "timestamp": 1642504560000,
        "signature": "HmnCaXySi8u1/qx9YlKA6cTU8L6HAydywDOpJjoLd+Bz+X93APaRXJ1yDJsTC95EPC29ESAisxQ2LsNF6ZSERA=="
      }
    }
  },
  "sender": "operator.prebidsso.com",
  "receiver": "cmp.com",
  "timestamp": 1643097663000,
  "signature": "S/Iz2+aEmD/j46J0Brq36BY3WZw8WVmv9TApCfplbB+c5EnG9jzStnplC1O8evn608nnVFiq3fvHSuQgkiMgrw=="
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/postIdsPrefsResponse.json
{
  "body": {
    "identifiers": [
      {
        "version": 0,
        "type": "paf_browser_id",
        "value": "7435313e-caee-4889-8ad7-0acd0114ae3c",
        "source": {
          "domain": "operator.prebidsso.com",
          "timestamp": 1642504380000,
          "signature": "Oiwt1PFNSJvhQQqpnmqS2jG1jc5pD1vDN/ZU+Diy2ohzGTd4AL2VF6REUOSseitMhVYk4LkYD2IsRXT1hkw5nQ=="
        }
      }
    ],
    "preferences": {
      "version": 0,
      "data": {
        "use_browsing_for_personalization": true
      },
      "source": {
        "domain": "cmp.com",
        "timestamp": 1642504560000,
        "signature": "OFgRb5njIf+HCmYHVM9IbEUoA90ZZL4wTlFDpPc+APSWAD4eCSclOzRV5i4LOlyyuu2Rkl+jAt2DC0UD1bVGiA=="
      }
    }
  },
  "sender": "operator.prebidsso.com",
  "receiver": "cmp.com",
  "timestamp": 1643097663000,
  "signature": "V32x2oL3QdvH2XlGG9NwscGpOyxAN7qII0hYhQZyTf1fLN3TCpNmrnegHqoDTdclTsOLY5eEdZ5m2kQG5cKTAw=="
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/getNewIdResponse.json
{
  "body": {
    "identifiers": [
      {
        "persisted": false,
        "version": 0,
        "type": "paf_browser_id",
        "value": "2e71121a-4feb-4a34-b7d1-839587d36390",
        "source": {
          "domain": "operator.pafdemo.com",
          "timestamp": 1643041140,
          "signature": "TcoSmz8xSfQIqlIa3RT9XItd7wkvnKWO6UeUjCy52Cn+O4rBXjwkm934ufZRyfM9ylrepQDPJlCSy/eEZxeAMw=="
        }
      }
    ]
  },
  "sender": "operator.pafdemo.com",
  "receiver": "cmp.com",
  "timestamp": 1646157887,
  "signature": "P+qBGqTLdX4GiTkkkozpxpCxzAnEJ9hWSrZWZmP5j82gtlM5JYG7dt8GAUTm9Ens763kWVg7bDm/UzG1To7egg=="
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/postIdsPrefsRequest.json
{
  "body": {
    "identifiers": [
      {
        "version": 0,
        "type": "paf_browser_id",
        "value": "7435313e-caee-4889-8ad7-0acd0114ae3c",
        "source": {
          "domain": "operator.prebidsso.com",
          "timestamp": 1642504380000,
          "signature": "Oiwt1PFNSJvhQQqpnmqS2jG1jc5pD1vDN/ZU+Diy2ohzGTd4AL2VF6REUOSseitMhVYk4LkYD2IsRXT1hkw5nQ=="
        }
      }
    ],
    "preferences": {
      "version": 0,
      "data": {
        "use_browsing_for_personalization": true
      },
      "source": {
        "domain": "cmp.com",
        "timestamp": 1642504560000,
        "signature": "OFgRb5njIf+HCmYHVM9IbEUoA90ZZL4wTlFDpPc+APSWAD4eCSclOzRV5i4LOlyyuu2Rkl+jAt2DC0UD1bVGiA=="
      }
    }
  },
  "sender": "cmp.com",
  "receiver": "operator.prebidsso.com",
  "timestamp": 1643097660000,
  "signature": "gKN9yh5fzM0mrVglfoOuOOeic6QzAyrGcRdqIHpLLFluxfqKZGaLVa/BRz+4I2HaxXq2siX8ge7UD5C6LljPOg=="
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/postIdPrefsRequest.json
{
  "body": {
    "identifiers": [
      {
        "version": 0,
        "type": "prebid_id",
        "value": "7435313e-caee-4889-8ad7-0acd0114ae3c",
        "source": {
          "domain": "operator.prebidsso.com",
          "timestamp": 1642504380000,
          "signature": "RYGHYsBUEwMgFgOJ9aUQl7ywl4xnqdmwWIgPbaIowbXbmZAFKLa7mcBJQuWh1wEskpu57SHn2mmCF6V5+cESgw=="
        }
      }
    ],
    "preferences": {
      "version": 0,
      "data": {
        "opt_in": true
      },
      "source": {
        "domain": "cmp.com",
        "timestamp": 1642504560000,
        "signature": "HmnCaXySi8u1/qx9YlKA6cTU8L6HAydywDOpJjoLd+Bz+X93APaRXJ1yDJsTC95EPC29ESAisxQ2LsNF6ZSERA=="
      }
    }
  },
  "sender": "cmp.com",
  "receiver": "operator.prebidsso.com",
  "timestamp": 1643097660000,
  "signature": "rh5xZm+eoSwsmxMO0CKD/bhXor8IZEJc7YrhQZHw7HGsdmX4rqW2Ra4Mp4ZQf1ltIe/otu1Ot296CwSL5HUljA=="
}
