=== OneKey-Network/addressability-framework/mvp-spec/json-schemas/transmission-response.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Transmission Response",
    "description": "",
    "$id": "transmission-response",
    "type": "object",
    "properties": {
        "version": {
            "$ref": "version.json"
        },
        "receiver": {
            "$ref": "transmission-receiver.json"
        },
        "transaction_ids": {
            "type": "array",
            "items": {
                "description": "The transaction-ids of the Addressable Contents for which the Receiver want to participate to",
                "$ref": "transaction_id.json"
            }
        },
        "status": {
            "$ref": "transmission-status.json"
        },
        "details": {
            "$ref": "transmission-details.json"
        },
        "source": {
            "description": "Signature based on input:\n```\ntransmission_response.receiver                + '\\u2063' +\ntransmission_response.status                  + '\\u2063'\ntransmission_response.source.domain           + '\\u2063' +\ntransmission_response.source.timestamp        + '\\u2063' +\nseed.source.signature+ '\\u2063' +\ntransaction_ids[0] + '\\u2063' +\n... + '\\u2063' +\ntransaction_ids[n]\n```",
            "$ref": "source.json"
        },
        "children": {
            "type": "array",
            "items": {
                "$ref": "transmission-result.json"
            }
        }
    },
    "required": [
        "version",
        "receiver",
        "transaction_ids",
        "status",
        "details",
        "source",
        "children"
    ]
}

=== OneKey-Network/addressability-framework/mvp-spec/partials/transmission-response-with-children.json
{
    "version": "0.1",
    "receiver": "ssp1.com",
    "status": "success",
    "details": "",
    "transaction_ids": [
        "4640dc9f-385f-4e02-a0e5-abbf241af94d",
        "7d71a23a-fafa-449a-8b85-63a634780107" 
    ],
    "source": {
        "domain": "ssp1.com",
        "timestamp": 1639589531,
        "signature": "d01c6e83f14b4f057c2a2a86d320e2454fc0c60df4645518d993b5f40019d24c"
    },
    "children": [
        {
            "version": "0.1",
            "receiver": "ssp2.com",
            "status": "success",
            "details": "",
            "transaction_ids": [
                "4640dc9f-385f-4e02-a0e5-abbf241af94d"
            ],
            "source": {
                "domain": "ssp2.com",
                "timestamp": 1639589531,
                "signature": "4ed0d811a96e424cdcbe8b85cd4e58bc75f3b6d701870fb4a2a620feee670d54"
            }
        },
        {
            "version": "0.1",
            "receiver": "dsp.com",
            "status": "success",
            "details": "",
            "transaction_ids": [
                "4640dc9f-385f-4e02-a0e5-abbf241af94d"
            ],
            "source": {
                "domain": "dsp.com",
                "timestamp": 1639589531,
                "signature": "b9d2918542e4a4155e5e404cf3d6e73449152c974da1e8f554282d7ed7c62278"
            }
        }
    ]
}
